---
- hosts: elasticsearch
  gather_facts: true
  become: true
  vars:
    slack_deployed_app_name: "elasticsearch"
    slack_deployed_app_version: "{{ es_version }}"
    slack_deployed_domain: "{{ es_slack_deployed_domain }}"
  pre_tasks:
    - include_tasks: tasks/slack-start.yml
      when: slack_notifications
  roles:
    - role: elastic.elasticsearch
    - role: certbot
      when: es_use_certbot == true
    - role: nginx
      when: es_use_nginx is not defined or es_use_nginx
  post_tasks:
    - include_tasks: tasks/slack-end.yml
      when: slack_notifications